name: 'XML reformat'
description: 'Reformat XML files'

inputs:
  config:
    description: "The config file for xmlformat"
    required: false
    default: ""

  exclude-files:
    description: "Exclude XML files from reformatting"
    required: false
    default: ""

  extensions:
    description: "Define file extensions for XML files (without dots or globs)"
    required: false
    default: "xml"

runs:
  using: "composite"
  steps:

    - id: whereis-xmlformat-output
      shell: bash
      run: |
        sudo apt-get install wget xmlformat-ruby
        echo "::set-output name=xmlformat::$(whereis xmformat)"

    - id: reformat
      shell: bash
      run: |
        CONFIG="${{ inputs.config }}"
        ./xml-format-action.sh -v ${CONFIG:+--config-file $CONFIG} \
          --excludes ${{ inputs.exclude-files }} \
          --extensions "${{ inputs.extensions }}" \
          ${{ github.sha }}

branding:
    icon: "git-merge"
    color: "green"
