name: 'XML reformat'
description: 'Reformat XML files'

inputs:
  config:
    description: "The config file for xmlformat"
    required: false
    default: ""

  exclude-files:
    description: "Exclude XML files from reformatting"
    required: false
    default: ""
  
  include-files:
    description: "Include XML files for reformatting"
    required: false
    default: "*.xml xml/*.xml"

runs:
  using: "composite"
  steps:

    - id: whereis-xmlformat-output
      shell: bash
      run: |
        sudo apt-get install wget xmlformat-ruby
        echo "::set-output name=xmlformat::$(whereis xmformat)"

    - id: reformat
      shell: bash
      run: |
        CONFIG="${{ inputs.config }}"
        ./xml-format-action.sh -v ${CONFIG:+--config-file $CONFIG} \
          -e ${{ inputs.exclude-files }} \
          ${{ inputs.include-files }}
        

branding:
    icon: "git-merge"
    color: "green"
