---
on:
  push:
    paths:
      - 'tests/xml/*.xml'
      - 'tests/docbook/*.xml'

jobs:
  reformat-xml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Format XML
        uses: ./
        with:
          include-files: tests/xml/*.xml

      - name: Format DocBook XML
        uses: ./
        with:
          include-files: tests/docbook/*.xml
          config: https://github.com/openSUSE/daps/raw/main/etc/docbook-xmlformat.conf

      - name: Configure Git
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "XML Reformat Bot"

      - name: Commit
        run: |
          git commit --all -m"[Auto] Reformat XML Files" || true

      - name: Push
        run: |
            BRANCH="HEAD:${GITHUB_REF#refs/heads/}"
            URL="https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@github.com/${{github.repository}}.git"
            git push "$URL" "$BRANCH"