---
on:
  push:
    paths:
      - 'tests/xml/*.xml'
      - 'tests/docbook/*.xml'


jobs:
  reformat-xml:
    # Use only branches, but skip tags
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04

    steps:
      - name: List some important versions
        run: |
          bash --version
          echo "curl version..."
          curl --version || true
          echo "wget version..."
          wget --version || true

      - uses: actions/checkout@v2
        with:
           # Number of commits to fetch.
           # 0 indicates all history for all branches and tags.
           # This is absolutely needed for this action!
           fetch-depth: 0

      - name: Set Git user and email...
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "XML Reformat Bot"

      - name: List action metadata
        run: |
          echo -e "action     : ${{ github.action }}"
          echo -e "actor      : ${{ github.actor }}"
          echo -e "event_name : ${{ github.event_name }}"
          echo -e "job        : ${{ github.job }}"
          echo -e "ref        : ${{ github.ref }}"
          echo -e" repository : ${{ github.repository }}"
          echo -e "run_id     : ${{ github.run_id }}"
          echo -e "sha        : ${{ github.sha }}"
          echo -e "workflow   : ${{ github.workflow }}"
          echo -e "workspace  : ${{ github.workspace }}"

      # - name: Format XML
      #  id: reformat1
      #  uses: ./

      - name: Format DocBook XML
        id: reformat2
        uses: ./
        with:
          exclude-files: |
            tests/docbook/schemas.xml
          config: https://github.com/openSUSE/daps/raw/main/etc/docbook-xmlformat.conf
      
      - name: Checks if we have a tag
        id: isreftag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
              echo "::set-output name=istag::${{ true }}"
          else
              echo "::set-output name=istag::${{ false }}"
          fi

      - name: Check steps outputs
        run: |
           echo "istag=${{ steps.isreftag.outputs.istag }}"
           echo "steps.reformat1.outputs.xmlfound=${{ steps.reformat1.outputs.xmlfound }}"
           echo "steps.reformat2.outputs.xmlfound=${{ steps.reformat2.outputs.xmlfound }}"

      - name: Push
        # if: ${{ steps.isreftag.outputs.istag }} == 'false'
        if: ${{ steps.reformat1.outputs.xmlfound }} == true || ${{ steps.reformat2.outputs.xmlfound }} == true
        run: |
            # Remove any refs/*/ parts:
            BRANCH="${GITHUB_REF#refs/heads/}"
            # BRANCH="${BRANCH#refs/tags/}"
            URL="https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@github.com/${{github.repository}}.git"
            git push "$URL" "$BRANCH"