---
name: Reformat XML

on:
  push:
    paths:
      - 'tests/*.xml'
  #  tags-ignore:
  #    - "*"
  #  branches:
  #    # Reformatting should only occur on pull requests
  #    - "!main"
  #    - "!master"
  # pull_request:
  #  paths:
  #    - 'tests/*.xml'

jobs:
  reformat-xml:
    # Use only branches, but skip tags
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-18.04

    steps:
      - name: List some important versions
        run: |
          bash --version
          echo "curl version..."
          curl --version || true
          echo "wget version..."
          wget --version || true
          echo "jq --version..."
          jq --version || true

      - uses: actions/checkout@v2
        with:
           # Number of commits to fetch.
           # 0 indicates all history for all branches and tags.
           # This is absolutely needed for this action!
           fetch-depth: 0
      - run: git fetch

      # Find the PR associated with this push, if there is one.
      #- uses: jwalton/gh-find-current-pr@v1
      #  id: findPr
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      #- run: echo "Your PR is ${PR}"
      #  if: success() && steps.findPr.outputs.number
      #  env:
      #    PR: ${{ steps.findPr.outputs.pr }}

      - name: Set Git user and email...
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "XML Reformat Bot"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "::group::Output GitHub context..."
          echo "$GITHUB_CONTEXT"
          echo "::endgroup::"

      - name: List action metadata
        run: |
          echo "github.action     : ${{ github.action }}"
          echo "github.actor      : ${{ github.actor }}"
          echo "github.event_name : ${{ github.event_name }}"
          echo "github.job        : ${{ github.job }}"
          echo "github.ref        : ${{ github.ref }}"
          echo "github.base.ref   : ${{ github.event.pull_request.base.ref }}"
          echo "github.repository : ${{ github.repository }}"
          echo "github.run_id     : ${{ github.run_id }}"
          echo "github.sha        : ${{ github.sha }}"
          echo "github.workflow   : ${{ github.workflow }}"
          echo "github.workspace  : ${{ github.workspace }}"
          # echo "github.api.url    : $GITHUB_API_URL"

      # - name: Format XML
      #  id: reformat1
      #  uses: ./

      - name: Format DocBook XML
        id: dbxml
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exclude-files: |
            tests/schemas.xml
          config: https://github.com/openSUSE/daps/raw/main/etc/docbook-xmlformat.conf
          xmlformat-use-tag: 1.9
      
      - name: Check steps outputs
        run: |
           echo "istag=${{ steps.isreftag.outputs.istag }}"
           # echo "steps.reformat1.outputs.xmlfound=${{ steps.reformat1.outputs.xmlfound }}"
           echo "steps.dbxml.outputs.xmlfound=${{ steps.dbxml.outputs.xmlfound }}"

      - name: Push
        if: ${{ steps.dbxml.outputs.xmlfound }}
        run: |
            # Remove any refs/heads/ parts:
            BRANCH="${GITHUB_REF#refs/heads/}"
            URL="https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
            git push "$URL" "$BRANCH"
