on:
  push:
    paths:
      - 'tests/xml/*.xml'

jobs:
  reformat-xml:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      uses: ./
      with:
        include: tests/xml/*.xml
    
    - name: Configure Git
      run: |
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name "XML Reformat Bot"
    
    - name: Commit
      run: |
        git commit --all -m"Reformat XML Files to common format." || true
    
    - name: Push
        run: |
          git push "https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@github.com/${{github.repository}}.git" "HEAD:${{ env.GIT_BRANCH }}"